# 프라미스 체이닝

순차적인 비동기 작업이 여러 개 있을 때 이를 프라미스를 이용해서 해결하는 방법을 만들어보자.

프라미스 체이닝은 아래와 같은 형태로 이루어진다. 

```js
new Promise(function(resolve, reject) {

  setTimeout(() => resolve(1), 1000); // (*)

}).then(function(result) { // (**)

  alert(result); // 1
  return result * 2;

}).then(function(result) { // (***)

  alert(result); // 2
  return result * 2;

}).then(function(result) {

  alert(result); // 4
  return result * 2;

});
```

프라미스 체이닝은 result가 .then 핸들러의 체인을 통해 전달되는 점에서 착안한다. 프라미스 체이닝은 직렬로도 가능하지만 병렬로도 처리가 가능하다. 다음 예시처럼도 가능하다. 

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve(1), 1000);
});

promise.then(function(result) {
  alert(result); // 1
  return result * 2;
});

promise.then(function(result) {
  alert(result); // 1
  return result * 2;
});

promise.then(function(result) {
  alert(result); // 1
  return result * 2;
});
```

프라미스는 하나고 등록된 핸들러는 여러 개이다. 

## 프라미스 변환하기

.then에 사용된 핸들러가 프라미스를 생성하거나 반환하는 경우도 있다. new Promise로 선언하고 .then 핸들러를 연결해 

```js
new Promise(function(resolve, reject) {

  setTimeout(() => resolve(1), 1000);

}).then(function(result) {

  alert(result); // 1

  return new Promise((resolve, reject) => { // (*)
    setTimeout(() => resolve(result * 2), 1000);
  });

}).then(function(result) { // (**)

  alert(result); // 2

  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  });

}).then(function(result) {

  alert(result); // 4

});
```

loadScript의 프로미스 형식.

```js
loadScript("/article/promise-chaining/one.js")
  .then(script => loadScript("/article/promise-chaining/two.js"))
  .then(script => loadScript("/article/promise-chaining/three.js"))
  .then(script => {
    // 스크립트를 정상적으로 불러왔기 때문에 스크립트 내의 함수를 호출할 수 있습니다.
    one();
    two();
    three();
  });
```

## thenable

핸들러는 프라미스가 아닌 thenable을 반환하기도 한다. .then이라는 메서드를 가진 객체는 모두 thenable 객체라고 부르는데, 이 객체는 프라미스와 같은 방식으로 처리된다. 

예를들어, thenable 객체는 다음과 같이 정의할 수 있다. 

## fetch와 체이닝 함께 응용하기

fetch를 이용하여 원격 서버에서 정보를가져올 수 있다. 

```js
// user.json에 요청을 보냅니다.
fetch('/article/promise-chaining/user.json')
  // 응답받은 내용을 json으로 불러옵니다.
  .then(response => response.json())
  // GitHub에 요청을 보냅니다.
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  // 응답받은 내용을 json 형태로 불러옵니다.
  .then(response => response.json())
  // 3초간 아바타 이미지(githubUser.avatar_url)를 보여줍니다.
  .then(githubUser => {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => img.remove(), 3000); // (*)
  });
```

## 참고

```js
promise.then(f1).catch(f2);

promise.then(f1, f2);
```

위의 코드와 아래 코드는 다를까?

다르다! 왜냐하면 위의 코드는 f1에서 발생한 오류를 catch를 이용하여 전달해주지만, 아래 코드는 f1에 해당하는 오류를 처리하지 못한다. 