# panic
panic!이 발생하면 프로그램은 되감기를 싲작한다. 러스트가 패닉을 마주친 함수로부터 스택을 거꾸로 훑으며 데이터를 제거한다. 다른 방법으로 즉시 그만두기가 있는데, 이는 데이터 쩨거 없이 프로그램을 쫑료한다. 되감기는 그만두기에 비해 일이 많으므로 릴리즈 모드에서 panic!으로 그만두기를 사용하고 싶은 경우, 아래와 같은 코드를 Cargo.toml에 추가한다. 
```rs
[profile.release]
panic = 'abort'
```

코드에서 직접 panic!을 호출하는 것이 아닌 다른 요인에 의해 발생되는 경우를 살펴보자. 
```rs
fn main() {
    let v = vec![1, 2, 3];

    v[99];
}
```
러스트는 메모리 영역이 벡터의 소유가 아닌 곳을 읽는 버퍼 오버로드를 방지하기 위해 존재하지 않는 인덱스 상 요소를 읽으려고 한다면 실행을 멈추고 거부한다. 이 에러는 우리가 작성하지 않은 파일인 libcollections/vec.rs에서 발생한다. 표준 라이브러리 내의 Vec<T>의 구현 부분이다. 이 곳에서 panic!이 실제로 발생한다. 

백트레이스: 어떤 지점에 도달하기까지 호출해온 모든 함수의 리스트. `RUST_BACKTRACE=1 cargo run`을 실행시키면 확인할 수 있다. 

# Result
Result열거형은 다음과 같은 variant를 갖는 열거형이다. 
```rs
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
T, E는 각각 제너릭 타입 파라미터이다. T는 성공한 경우, E는 실패한 경우를 나타낸다. 다음은 Result의 값을 반환하는 함수이다. Result도 마찬가지로 Ok와 Err앞에 Result::을 붙이지 않아도 된다. 
```rs
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("There was a problem opening the file: {:?}", error)
        },
    };
}
```
위의 코드는 File::open이 실패한 이유에 상관없이 panic!을 일으킨다. 이를 조건마다 다르게 나눶주고 싶은 경우 다음과 같이 구현할 수 있다. 
```rs
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(ref error) if error.kind() == ErrorKind::NotFound => { // 매치가드
            match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => {
                    panic!(
                        "Tried to create file but there was a problem: {:?}",
                        e
                    )
                },
            }
        },
        Err(error) => {
            panic!(
                "There was a problem opening the file: {:?}",
                error
            )
        },
    };
}
```

Err variant 내에 있는 File::open이 반환하는 값의 타입은 io:Error인데, 이는 표준 라이브러리에서 제공하는 구조체로 이 구조체는 kind 메서드를 제공한다. 따라서 ErrorKind::NotFound를 매칭하여 파일이 존재하지 않음을 확인할 수 있다. 

ref: 값을 매치하여 그 참조자를 제공. &는 참조자를 매치하고 그 값을 제공. 매치 가드에서 확인하고자 하는 조건문은 error.kind()에 의해 반환된 값이 ErrorKind 열거형의 NotFound variant인가 하는 것이다. 그렇다면 File::create로 파일 생성을 시도하고, 이 또한 실패가능하기에 match구분을 바깥쪽으로 마찬가지로 추가할 핖요가 있다. 

unwrap: match의 사용은 잘 동작하지만, 항상 잘 전달하지 않기에, unwrap을 활용할 수 있다. Result가 Err라면, unwrap은 panic!을 호출한다. 

expect: unwrap에서 에러 메세지 출력을 선택하게 한다. unwrap과 expect는 같은 방식으로 동작한다. 

에러 전파: 실패할지 모르는 무언가를 위해, 에러 처리 대신 에러를 호출하는 코드를 반환할 수 있다. 에러 전파의 숏컷으로 ? 사용가능. ?는 Result를 반환하는 함수 내에서 사용가능하다. main은 ()를 반환하므로 사용할 수 없다. 
```rs
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

# 언제 panic을?
panic과 Result의 차이: 복구 가능 여부. Result는 코드에서 결단을 내려주기보다 옵션을 제공하는 것. 실패할지도 모르는 함수를 정의할 때는 Result를 반환하는 것이 기본적인 좋은 선택이다. 한편, 예제, 프로토타입 코드, 테스트의 경우는 panic이 더 좋다. 예제안에 에러처리코드를 넣는 것은 예제를 덜 깨끗하게 만들 수 있다. 또한 테스트의 경우 해당 메서드가 테스트 중인 기능이 아니더라도 전체 테스트를 실패시키도록 한다. 

에러 처리의 가이드라인: 나쁜 상태란 어떤 가정, 보장, 계약, 불변성이 깨질 때를 의미한다. 나쁜 상태에 처하게 될 가능성이 있다면 panic!을 넣는 것이 바람직하다. 

나쁜 상태의 성질
1. 나쁜 상태란 가끔 벌어질 것으로 예상되는 무언가가 아니다. 
2. 그 시점 이후의 코드는 나쁜 상태에 있지 않아야만 할 필요가 있다.
3. 사용하고 있는 타입 내에 이 정보를 넣을만한 뾰족한 수가 없다. 

예상되는 나쁜 상태에 도달하는 경우라면 Result를 반환하는 것이 더 적절하다. 

결국, panic과 Result의 차이는 프로그램의 처리 가능여부이다. Result 열거형은 러스트의 타입 시스템을 이용하여 코드가 복구할 수 있는 방법으로 연산이 실패할 수 있음을 알려준다. 